kind: Pod
apiVersion: v1
metadata:
  name: argocd-app
  labels:
    app: argocd-app
spec:
  containers:
    - name: argocd-app
      image: hashicorp/http-echo
      args:
        - "-text=argocd"
      resources:
        limits:
          cpu: "100m"
          memory: "100Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: argocd-service
spec:
  selector:
    app: argocd-app
  ports:
    - port: 5678
      targetPort: 5678

---

kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels:
    app: apple-app
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple"
      resources:
        limits:
          cpu: "100m"
          memory: "100Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: apple-service
spec:
  selector:
    app: apple-app
  ports:
    - port: 5678
      targetPort: 5678

---

kind: Pod
apiVersion: v1
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  containers:
    - name: demo-app
      image: hashicorp/http-echo
      args:
        - "-text=demo"
      resources:
        limits:
          cpu: "100m"
          memory: "100Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: demo-service
spec:
  selector:
    app: demo-app
  ports:
    - port: 5678
      targetPort: 5678