apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-db
  namespace: pg-clusters
spec:
  instances: 2
  enableSuperuserAccess: true
  resources:
    requests:
      memory: "256Mi"
      cpu: 250m
    limits:
      memory: "256Mi"
      cpu: 250m

  storage:
    size: 1Gi

  backup:
    barmanObjectStore:
      destinationPath: s3://test-backup-k8s/backups
      wal:
        compression: gzip
        encryption: AES256
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: "20d"